from capstone import *
from capstone.x86_const import *

###############################################################################
# Implicit registers
# instruction_name: list of (access_type, size, reg_name)
###############################################################################
mem_override = {
        X86_INS_JMP:
        [('r', 8)]
}

implicit_regs = {
    X86_INS_AAA:
        [('rw',4,'EFLAGS'),
         ('rw',1,'AL')],
    X86_INS_AAD:
        [('w',4,'EFLAGS'),
         ('rw',4,'EAX')],
    X86_INS_AAM:
        [('w',4,'EFLAGS'),
         ('rw',4,'EAX')],
    X86_INS_AAS:
        [('w',4,'EFLAGS'),
         ('rw',4,'EAX')],
    X86_INS_FABS:
        [('rw',10,'ST(0)')],
    X86_INS_ADC:
        [('rw',4,'EFLAGS')],
    X86_INS_ADCX:
        [('rw',4,'EFLAGS')],
    X86_INS_ADD:
        [('w',4,'EFLAGS')],
    X86_INS_RDMSR:
        [('r',4,'ECX'),
         ('w',4,'EAX'),
         ('w',4,'EDX')],
    X86_INS_RCR:
        [('rw',4,'EFLAGS')],
    X86_INS_FADD:
        [('rw',10,'ST(0)')],
    X86_INS_FIADD:
        [('rw',4,'ST(0)')],
    #X86_INS_FADDP:
    #    [('rw',10,'ST(0)')],
    X86_INS_FLDPI:
        [('w',10,'ST(0)')],
    X86_INS_AND:
        [('w',4,'EFLAGS')],
    X86_INS_ANDN:
        [('w',4,'EFLAGS')],
    X86_INS_ARPL:
        [('w',4,'EFLAGS')],
    X86_INS_BEXTR:
        [('w',4,'EFLAGS')],
    X86_INS_RDTSC:
        [('r',4,'ECX'),
         ('w',4,'EAX'),
         ('w',4,'EDX')],
    X86_INS_BLSI:
        [('w',4,'EFLAGS')],
    X86_INS_BLSIC:
        [('w',4,'EFLAGS')],
    X86_INS_BLSMSK:
        [('w',4,'EFLAGS')],
    X86_INS_BLSR:
        [('w',4,'EFLAGS')],
    X86_INS_RDTSCP:
        [('w',4,'EAX'),
         ('w',4,'ECX'),
         ('w',4,'EDX')],
    X86_INS_BSF:
        [('w',4,'EFLAGS')],
    X86_INS_BSR:
        [('w',4,'EFLAGS')],
    X86_INS_BT:
        [('w',4,'EFLAGS')],
    X86_INS_BTC:
        [('rw',4,'EFLAGS')],
    X86_INS_ROL:
        [('w',4,'EFLAGS')],
    X86_INS_BTS:
        [('rw',4,'EFLAGS')],
    X86_INS_BZHI:
        [('w',4,'EFLAGS')],
    X86_INS_CALL:
        [('rw',4,'ESP'),
         ('rw',4,'EIP')],
    X86_INS_POPCNT:
        [('w',4,'EFLAGS')],
    X86_INS_CDQ:
        [('rw',4,'EAX'),
         ('w',4,'EDX')],
    X86_INS_CMP:
        [('w',4,'EFLAGS')],
    X86_INS_POPFQ:
        [('r',4,'ESP'),
         ('w',4,'EFLAGS')],
    X86_INS_CLC:
        [('w',4,'EFLAGS')],
    X86_INS_CLD:
        [('w',4,'EFLAGS')],
    X86_INS_PREFETCHW:
        [('w',4,'EFLAGS')],
    X86_INS_CLI:
        [('w',4,'EFLAGS')],
    X86_INS_CMC:
        [('rw',4,'EFLAGS')],
    X86_INS_CMOVA:
        [('r',4,'EFLAGS')],
    X86_INS_CMOVAE:
        [('r',4,'EFLAGS')],
    X86_INS_CMOVB:
        [('r',4,'EFLAGS')],
    X86_INS_CMOVBE:
        [('r',4,'EFLAGS')],
    X86_INS_FCMOVBE:
        [('r',4,'EFLAGS')],
    X86_INS_FCMOVB:
        [('r',4,'EFLAGS')],
    X86_INS_CMOVE:
        [('r',4,'EFLAGS')],
    X86_INS_FCMOVE:
        [('r',4,'EFLAGS')],
    X86_INS_CMOVG:
        [('r',4,'EFLAGS')],
    X86_INS_CMOVGE:
        [('r',4,'EFLAGS')],
    X86_INS_CMOVL:
        [('r',4,'EFLAGS')],
    X86_INS_CMOVLE:
        [('r',4,'EFLAGS')],
    X86_INS_FCMOVNBE:
        [('r',4,'EFLAGS')],
    X86_INS_FCMOVNB:
        [('r',4,'EFLAGS')],
    X86_INS_CMOVNE:
        [('r',4,'EFLAGS')],
    X86_INS_FCMOVNE:
        [('r',4,'EFLAGS')],
    X86_INS_CMOVNO:
        [('r',4,'EFLAGS')],
    X86_INS_CMOVNP:
        [('r',4,'EFLAGS')],
    X86_INS_FCMOVNU:
        [('r',4,'EFLAGS')],
    X86_INS_CMOVNS:
        [('r',4,'EFLAGS')],
    X86_INS_CMOVO:
        [('r',4,'EFLAGS')],
    X86_INS_CMOVP:
        [('r',4,'EFLAGS')],
    X86_INS_FCMOVU:
        [('r',4,'EFLAGS')],
    X86_INS_CMOVS:
        [('r',4,'EFLAGS')],
    X86_INS_ROR:
        [('w',4,'EFLAGS')],
    X86_INS_CMPSB:
        [('w',4,'EFLAGS')],
    X86_INS_CMPSQ:
        [('w',4,'EFLAGS')],
    X86_INS_CMPSW:
        [('w',4,'EFLAGS')],
    X86_INS_CMPXCHG:
        [('w',4,'EFLAGS'),
         ('rw',4,'EAX')],
    X86_INS_RSM:
        [('w',4,'EFLAGS')],
    X86_INS_COMISD:
        [('w',4,'EFLAGS')],
    X86_INS_COMISS:
        [('w',4,'EFLAGS')],
    X86_INS_SAHF:
        [('w',4,'EFLAGS'),
         ('r',1,'EAX')],
    X86_INS_SAL:
        [('w',4,'EFLAGS')],
    X86_INS_SAR:
        [('w',4,'EFLAGS')],
    X86_INS_FCOS:
        [('rw',10,'ST(0)')],
    X86_INS_SBB:
        [('rw',4,'EFLAGS')],
    X86_INS_SCASB:
        [('rw',4,'EFLAGS'),
         ('rw',4,'EDI')],
    X86_INS_SCASD:
        [('rw',4,'EFLAGS'),
         ('rw',4,'EDI')],
    X86_INS_SCASQ:
        [('rw',4,'EFLAGS'),
         ('rw',4,'EDI')],
    X86_INS_SCASW:
        [('rw',4,'EFLAGS'),
         ('rw',4,'EDI')],
    X86_INS_SETAE:
        [('r',4,'EFLAGS')],
    X86_INS_SETA:
        [('r',4,'EFLAGS')],
    X86_INS_SETBE:
        [('r',4,'EFLAGS')],
    X86_INS_SETB:
        [('r',4,'EFLAGS')],
    X86_INS_SETE:
        [('r',4,'EFLAGS')],
    X86_INS_SETGE:
        [('r',4,'EFLAGS')],
    X86_INS_SETG:
        [('r',4,'EFLAGS')],
    X86_INS_SETLE:
        [('r',4,'EFLAGS')],
    X86_INS_SETL:
        [('r',4,'EFLAGS')],
    X86_INS_SETNE:
        [('r',4,'EFLAGS')],
    X86_INS_SETNO:
        [('r',4,'EFLAGS')],
    X86_INS_SETNP:
        [('r',4,'EFLAGS')],
    X86_INS_SETNS:
        [('r',4,'EFLAGS')],
    X86_INS_SETO:
        [('r',4,'EFLAGS')],
    X86_INS_SETP:
        [('r',4,'EFLAGS')],
    X86_INS_CWDE:
        [('rw',4,'EAX')],
    X86_INS_DAA:
        [('rw',4,'EFLAGS'),
         ('rw',4,'EAX')],
    X86_INS_DAS:
        [('rw',4,'EFLAGS'),
         ('rw',4,'EAX')],
    X86_INS_DEC:
        [('w',4,'EFLAGS'),
         ('rw',4,'EAX')],
    X86_INS_DIV:
        [('w',4,'EFLAGS'),
         ('rw',4,'EAX'),
         ('rw',4,'EDX')],
    X86_INS_FIDIVR:
        [('rw',10,'ST(0)')],
    X86_INS_SHL:
        [('w',4,'EFLAGS')],
    X86_INS_SHLD:
        [('rw',4,'EFLAGS')],
    X86_INS_SHR:
        [('w',4,'EFLAGS')],
    X86_INS_SHRD:
        [('rw',4,'EFLAGS')],
    X86_INS_FDIVP:
        [('rw',10,'ST(0)')],
    X86_INS_FCOM:
        [('r',10,'ST(0)')],
    X86_INS_FSIN:
        [('rw',10,'ST(0)')],
    X86_INS_CQO:
        [('rw',4,'EAX'),
         ('w',4,'EDX')],
    X86_INS_ENTER:
        [('r',4,'EBP'),
         ('rw',4,'ESP')],
    X86_INS_F2XM1:
        [('rw',10,'ST(0)')],
    X86_INS_FSQRT:
        [('rw',10,'ST(0)')],
    X86_INS_FBSTP:
        [('rw',10,'ST(0)')],
    X86_INS_STC:
        [('w',4,'EFLAGS')],
    X86_INS_STD:
        [('w',4,'EFLAGS')],
    X86_INS_STI:
        [('w',4,'EFLAGS')],
    X86_INS_FICOM:
        [('r',4,'ST(0)')],
    X86_INS_STOSB:
        [('rw',4,'ESI')],
    X86_INS_STOSD:
        [('rw',4,'ESI')],
    X86_INS_STOSQ:
        [('rw',4,'ESI')],
    X86_INS_STOSW:
        [('rw',4,'ESI')],
    X86_INS_FLDL2E:
        [('w',10,'ST(0)')],
    X86_INS_FLDL2T:
        [('w',10,'ST(0)')],
    X86_INS_FLDLG2:
        [('w',10,'ST(0)')],
    X86_INS_FLDLN2:
        [('w',10,'ST(0)')],
    X86_INS_FXCH:
        [('rw',10,'ST(0)'),
         ('w',10,'ST(1)')],
    X86_INS_FISUBR:
        [('rw',10,'ST(0)')],
    X86_INS_FPATAN:
        [('rw',10,'ST(0)'),
         ('rw',10,'ST(1)')],
    X86_INS_FPREM:
        [('rw',10,'ST(0)'),
         ('r',10,'ST(1)')],
    X86_INS_FPREM1:
        [('rw',10,'ST(0)'),
         ('r',10,'ST(1)')],
    X86_INS_FISUB:
        [('rw',10,'ST(0)')],
    X86_INS_FSUBP:
        [('rw',10,'ST(0)')],
    X86_INS_FRNDINT:
        [('rw',10,'ST(0)')],
    X86_INS_FRSTOR:
        [('w',10,'ST(0)'),
         ('w',10,'ST(1)'),
         ('w',10,'ST(2)'),
         ('w',10,'ST(3)'),
         ('w',10,'ST(4)'),
         ('w',10,'ST(5)'),
         ('w',10,'ST(6)'),
         ('w',10,'ST(7)')],
    X86_INS_FSCALE:
        [('rw',10,'ST(0)'),
         ('r',10,'ST(1)')],
    X86_INS_TEST:
        [('w',4,'EFLAGS')],
    X86_INS_FXAM:
        [('rw',10,'ST(0)')],
    X86_INS_FTST:
        [('r',10,'ST(0)')],
    X86_INS_TZCNT:
        [('w',4,'EFLAGS')],
    X86_INS_FXTRACT:
        [('rw',10,'ST(0)')],
    X86_INS_FYL2X:
        [('rw',10,'ST(0)'),
         ('w',10,'ST(1)')],
    X86_INS_FYL2XP1:
        [('rw',10,'ST(0)'),
         ('w',10,'ST(1)')],
    X86_INS_FUCOM:
        [('rw',10,'ST(0)'),
         ('rw',10,'ST(1)')],
    X86_INS_FIDIV:
        [('rw',10,'ST(0)')],
    X86_INS_CPUID:
        [('rw',4,'EAX'),
         ('w',4,'EBX'),
         ('w',4,'ECX'),
         ('w',4,'EDX')],
    X86_INS_IDIV:
        [('w',4,'EFLAGS'),
         ('rw',4,'EAX'),
         ('rw',4,'EDX')],
    X86_INS_FILD:
        [('w',10,'ST(0)')],
    X86_INS_IMUL:
        [('rw',4,'EFLAGS'),
         ('rw',4,'EAX'),
         ('rw',4,'EDX')],
    X86_INS_INC:
        [('w',4,'EFLAGS')],
    X86_INS_INSB:
        [('rw',4,'EDI')],
    X86_INS_INSD:
        [('rw',4,'EDI')],
    X86_INS_INSW:
        [('rw',4,'EDI')],
    X86_INS_POPF:
        [('r',4,'ESP'),
         ('w',4,'EFLAGS')],
    X86_INS_IRET:
        [('w',4,'EIP'),
         ('rw',4,'ESP')],
    X86_INS_FISTTP:
        [('r',10,'ST(0)')],
    X86_INS_FIST:
        [('r',10,'ST(0)')],
    X86_INS_FISTP:
        [('rw',10,'ST(0)'),
         ('r',10,'ST(1)')],
    X86_INS_UCOMISD:
        [('w',4,'EFLAGS')],
    X86_INS_UCOMISS:
        [('w',4,'EFLAGS')],
    X86_INS_VERR:
        [('w',4,'EFLAGS')],
    X86_INS_CDQE:
        [('rw',4,'EAX')],
    X86_INS_FUCOMPP:
        [('rw',10,'ST(0)'),
         ('rw',10,'ST(1)')],
    X86_INS_JMP:
        [('w',4,'EIP')],
    X86_INS_JAE:
        [('r',4,'EFLAGS'),
         ('rw',4,'EIP')],
    X86_INS_JA:
        [('r',4,'EFLAGS'),
         ('rw',4,'EIP')],
    X86_INS_JBE:
        [('r',4,'EFLAGS'),
         ('rw',4,'EIP')],
    X86_INS_JB:
        [('r',4,'EFLAGS'),
         ('rw',4,'EIP')],
    X86_INS_POPFD:
        [('r',4,'ESP'),
         ('w',4,'EFLAGS')],
    X86_INS_JE:
        [('r',4,'EFLAGS'),
         ('rw',4,'EIP')],
    X86_INS_JGE:
        [('r',4,'EFLAGS'),
         ('rw',4,'EIP')],
    X86_INS_JG:
        [('r',4,'EFLAGS'),
         ('rw',4,'EIP')],
    X86_INS_JLE:
        [('r',4,'EFLAGS'),
         ('rw',4,'EIP')],
    X86_INS_JL:
        [('r',4,'EFLAGS'),
         ('rw',4,'EIP')],
    X86_INS_VERW:
        [('w',4,'EFLAGS')],
    X86_INS_JNE:
        [('r',4,'EFLAGS'),
         ('rw',4,'EIP')],
    X86_INS_JNO:
        [('r',4,'EFLAGS'),
         ('rw',4,'EIP')],
    X86_INS_JNP:
        [('r',4,'EFLAGS'),
         ('rw',4,'EIP')],
    X86_INS_JNS:
        [('r',4,'EFLAGS'),
         ('rw',4,'EIP')],
    X86_INS_JO:
        [('r',4,'EFLAGS'),
         ('rw',4,'EIP')],
    X86_INS_JP:
        [('r',4,'EFLAGS'),
         ('rw',4,'EIP')],
    X86_INS_JS:
        [('r',4,'EFLAGS'),
         ('rw',4,'EIP')],
    X86_INS_WRMSR:
        [('r',4,'ECX'),
         ('r',4,'EAX'),
         ('r',4,'EDX')],
    X86_INS_FPTAN:
        [('rw',10,'ST(0)'),
         ('w',10,'ST(1)')],
    X86_INS_CMPSS:
        [('w',4,'EFLAGS')],
    X86_INS_CWD:
        [('rw',4,'EAX'),
         ('w',4,'EDX')],
    X86_INS_LAHF:
        [('r',4,'EFLAGS'),
         ('w',4,'EAX')],
    X86_INS_LAR:
        [('w',4,'EFLAGS')],
    X86_INS_BTR:
        [('rw',4,'EFLAGS')],
    X86_INS_FLD1:
        [('w',10,'ST(0)')],
    X86_INS_FLD:
        [('w',10,'ST(0)')],
    X86_INS_LEAVE:
        [('w',4,'ESP'),
         ('rw',4,'EBP')],
    X86_INS_POP:
        [('rw',4,'ESP')],
    X86_INS_POPAW:
        [('r',4,'ESP'),
         ('w',4,'EDI'),
         ('w',4,'ESI'),
         ('w',4,'EBP'),
         ('w',4,'EBX'),
         ('w',4,'EDX'),
         ('w',4,'ECX'),
         ('w',4,'EAX')],
    X86_INS_OR:
        [('w',4,'EFLAGS')],
    X86_INS_SUB:
        [('w',4,'EFLAGS')],
    X86_INS_XOR:
        [('w',4,'EFLAGS')],
    X86_INS_LODSB:
        [('rw',4,'ESI')],
    X86_INS_LODSD:
        [('rw',4,'ESI')],
    X86_INS_POPAL:
        [('r',4,'ESP'),
         ('w',4,'EDI'),
         ('w',4,'ESI'),
         ('w',4,'EBP'),
         ('w',4,'EBX'),
         ('w',4,'EDX'),
         ('w',4,'ECX'),
         ('w',4,'EAX')],
    X86_INS_LODSW:
        [('rw',4,'ESI')],
    X86_INS_FDIV:
        [('rw',10,'ST(0)')],
    X86_INS_CBW:
        [('rw',4,'EAX')],
    X86_INS_XADD:
        [('w',4,'EFLAGS')],
    X86_INS_LZCNT:
        [('w',4,'EFLAGS')],
    X86_INS_MASKMOVDQU:
        [('r',4,'EDI')],
    X86_INS_CMPSD:
        [('w',4,'EFLAGS')],
    X86_INS_FCHS:
        [('rw',10,'ST(0)')],
    X86_INS_MASKMOVQ:
        [('r',4,'EDI')],
    X86_INS_RET:
        [('rw',4,'ESP'),
         ('w',4,'EIP')],
    X86_INS_FLDZ:
        [('w',10,'ST(0)')],
    X86_INS_PUSHFQ:
        [('r',4,'ESP'),
         ('r',4,'EFLAGS')],
    X86_INS_OUTSB:
        [('rw',4,'ESI')],
    X86_INS_RCL:
        [('rw',4,'EFLAGS')],
    X86_INS_PTEST:
        [('w',4,'EFLAGS')],
    X86_INS_MONITOR:
        [('r',4,'EAX'),
         ('r',4,'ECX'),
         ('r',4,'EDX')],
    X86_INS_PUSH:
        [('rw',4,'ESP')],
    X86_INS_PUSHAW:
        [('r',4,'ESP'),
         ('r',4,'EDI'),
         ('r',4,'ESI'),
         ('r',4,'EBP'),
         ('r',4,'EBX'),
         ('r',4,'EDX'),
         ('r',4,'ECX'),
         ('r',4,'EAX')],
    X86_INS_PUSHAL:
        [('r',4,'ESP'),
         ('r',4,'EDI'),
         ('r',4,'ESI'),
         ('r',4,'EBP'),
         ('r',4,'EBX'),
         ('r',4,'EDX'),
         ('r',4,'ECX'),
         ('r',4,'EAX')],
    X86_INS_PUSHF:
        [('r',4,'ESP'),
         ('r',4,'EFLAGS')],
    X86_INS_PUSHFD:
        [('r',4,'ESP'),
         ('r',4,'EFLAGS')],
    X86_INS_MUL:
        [('rw',4,'EAX'),
         ('w',4,'EDX')],
    X86_INS_LODSQ:
        [('rw',4,'ESI')],
    X86_INS_MULX:
        [('r',4,'EDX')],
    X86_INS_FMUL:
        [('w',10,'ST(0)')],
    X86_INS_FIMUL:
        [('rw',10,'ST(0)')],
    X86_INS_FMULP:
        [('w',10,'ST(0)')],
    X86_INS_MWAIT:
        [('r',4,'EAX'),
         ('r',4,'ECX'),
         ('r',4,'EDX')],
    X86_INS_NEG:
        [('w',4,'EFLAGS')],
    X86_INS_FST:
        [('r',10,'ST(0)')],
    X86_INS_OUTSD:
        [('rw',4,'ESI')],
    X86_INS_OUTSW:
        [('rw',4,'ESI')],
    X86_INS_FSTP:
        [('rw',10,'ST(0)')],
    X86_INS_PCMPESTRI:
        [('w',4,'EFLAGS'),
         ('r',4,'EAX'),
         ('w',4,'ECX'),
         ('r',4,'EDX')],
    X86_INS_PCMPESTRM:
        [('w',4,'EFLAGS'),
         ('r',4,'EAX'),
         ('w',4,'XMM0'),
         ('r',4,'EDX')],
    X86_INS_PCMPISTRI:
        [('w',4,'EFLAGS'),
         ('w',4,'ECX')],
    X86_INS_PCMPISTRM:
        [('w',4,'EFLAGS'),
         ('w',4,'XMM0')],
}

implicit_mem = {
    X86_INS_PUSH:   ('w',8),
    X86_INS_CALL:   ('w',8),
    X86_INS_RET:    ('r',8),
    X86_INS_ENTER:  ('w',8),
    X86_INS_RDMSR:  ('r',8),
    X86_INS_WRMSR:  ('w',8),
    X86_INS_POP:    ('r',8),
    X86_INS_POPF:   ('r',4),
    X86_INS_POPFD:  ('r',4),
    X86_INS_POPFQ:  ('r',8),
    X86_INS_PUSHF:  ('w',4),
    X86_INS_PUSHFD: ('w',4),
    X86_INS_PUSHFQ: ('w',8),
    X86_INS_LEAVE:  ('r',8),
    X86_INS_IRET:   ('r',8)
}

remove_mem = set([
    X86_INS_LEA])
